---- PATIENTS TABLE
CREATE TABLE PATIENTS (
    PATIENT_ID NUMBER PRIMARY KEY,
    FIRST_NAME VARCHAR2(50) NOT NULL,
    LAST_NAME VARCHAR2(50),
    GENDER VARCHAR2(10),
    DOB DATE,
    MOBILE_NUMBER VARCHAR2(15),
    EMAIL VARCHAR2(100),
    CREATED_DATE DATE DEFAULT SYSDATE
);

----DOCTORS TABLE
CREATE TABLE DOCTORS (
    DOCTOR_ID NUMBER PRIMARY KEY,
    DOCTOR_NAME VARCHAR2(100) NOT NULL,
    SPECIALIZATION VARCHAR2(100) NOT NULL,
    MOBILE_NO VARCHAR2(15) NOT NULL,
    CONSTRAINT UK_DOCTOR_MOBILE UNIQUE (MOBILE_NO)
);
o
----APPOINTMENTS TABLE
CREATE TABLE APPOINTMENTS (
    APPOINTMENT_ID NUMBER PRIMARY KEY,
    PATIENT_ID NUMBER NOT NULL,
    DOCTOR_ID NUMBER NOT NULL,
    APPOINTMENT_DATE DATE NOT NULL,
    STATUS VARCHAR2(20),

    CONSTRAINT FK_APPOINTMENT_PATIENT
        FOREIGN KEY (PATIENT_ID)
        REFERENCES PATIENTS(PATIENT_ID),

    CONSTRAINT FK_APPOINTMENT_DOCTOR
        FOREIGN KEY (DOCTOR_ID)
        REFERENCES DOCTORS(DOCTOR_ID)
);

----BILLS TABLE
CREATE TABLE BILLS (
    BILL_ID NUMBER PRIMARY KEY,
    PATIENT_ID NUMBER NOT NULL,
    APPOINTMENT_ID NUMBER NOT NULL,
    BILL_DATE DATE,
    CONSULTATION_FEE NUMBER(10,2),
    LAB_CHARGES NUMBER(10,2),
    MEDICINE_CHARGES NUMBER(10,2),
    TOTAL_AMOUNT NUMBER(10,2) NOT NULL,
    PAYMENT_STATUS VARCHAR2(20) NOT NULL,

    CONSTRAINT FK_BILL_PATIENT
        FOREIGN KEY (PATIENT_ID)
        REFERENCES PATIENTS(PATIENT_ID),

    CONSTRAINT FK_BILL_APPOINTMENT
        FOREIGN KEY (APPOINTMENT_ID)
        REFERENCES APPOINTMENTS(APPOINTMENT_ID)
);

----LAB_ORDERS TABLE
CREATE TABLE LAB_ORDERS (
    ORDER_ID NUMBER PRIMARY KEY,
    PATIENT_ID NUMBER,
    DOCTOR_ID NUMBER,
    ORDER_DATE DATE,
    STATUS VARCHAR2(20),
    CONSTRAINT FK_LAB_PATIENT
        FOREIGN KEY (PATIENT_ID)
        REFERENCES PATIENTS(PATIENT_ID),
    CONSTRAINT FK_LAB_DOCTOR
        FOREIGN KEY (DOCTOR_ID)
        REFERENCES DOCTORS(DOCTOR_ID)
);


