/*
-------------------------------------------------------
Hospital Management System
View : VW_HOSPITAL_DASHBOARD
Author : Vasavi
-------------------------------------------------------
*/

CREATE OR REPLACE VIEW VW_HOSPITAL_DASHBOARD AS
SELECT
    (SELECT COUNT(*) FROM PATIENTS) AS TOTAL_PATIENTS,
    (SELECT COUNT(*) FROM DOCTORS) AS TOTAL_DOCTORS,
    (SELECT COUNT(*) FROM APPOINTMENTS) AS TOTAL_APPOINTMENTS,
    (SELECT COUNT(*) FROM BILLS) AS TOTAL_BILLS,
    (SELECT NVL(SUM(TOTAL_AMOUNT), 0) FROM BILLS) AS TOTAL_REVENUE,
    (SELECT COUNT(*) FROM LAB_RESULTS) AS TOTAL_LAB_TESTS
FROM DUAL;
/
