/*
------------------------------------------------------------
Hospital Management System
Package : PKG_PATIENT
Author  : Vasavi
------------------------------------------------------------
*/
CREATE OR REPLACE PACKAGE PKG_PATIENT
AS
PROCEDURE REGISTER_PATIENT
(
P_FIRST_NAME IN VARCHAR2,
P_LAST_NAME IN VARCHAR2,
P_GENDER IN VARCHAR2,
P_DOB IN DATE,
P_MOBILE IN VARCHAR2,
P_EMAIL IN VARCHAR2
);
FUNCTION GET_PATIENT_AGE
(
P_PATIENT_ID NUMBER
)
RETURN NUMBER;
END PKG_PATIENT;
/


CREATE OR REPLACE PACKAGE BODY PKG_PATIENT
AS
PROCEDURE REGISTER_PATIENT
(
    P_FIRST_NAME IN VARCHAR2,
    P_LAST_NAME IN VARCHAR2,
    P_GENDER IN VARCHAR2,
    P_DOB IN DATE,
    P_MOBILE IN VARCHAR2,
    P_EMAIL IN VARCHAR2
)
IS
BEGIN
    INSERT INTO PATIENTS
(
    FIRST_NAME,
    LAST_NAME,
    GENDER,
    DOB,
    MOBILE_NUMBER,
    EMAIL
)
VALUES
(
    P_FIRST_NAME,
    P_LAST_NAME,
    P_GENDER,
    P_DOB,
    P_MOBILE,
    P_EMAIL
);

    COMMIT;
END REGISTER_PATIENT;

FUNCTION GET_PATIENT_AGE
(
P_PATIENT_ID NUMBER
)
RETURN NUMBER
IS
V_DOB DATE;
V_AGE NUMBER;
BEGIN
SELECT DOB
INTO V_DOB
FROM PATIENTS
WHERE PATIENT_ID=P_PATIENT_ID;

V_AGE:=FLOOR(MONTHS_BETWEEN(SYSDATE,V_DOB)/12);
RETURN V_AGE;
EXCEPTION
WHEN NO_DATA_FOUND THEN
RETURN NULL;
END GET_PATIENT_AGE;
END PKG_PATIENT;
/
